name: Cypress Tests

on:
  workflow_dispatch:
      inputs:
        cli:
          description: Run by cypress command line
          default: yarn cypress run
jobs:
  cypress-electron-teste:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v6.0.2

      - name: Install dependencies
        run: yarn install

      - name: Run E2E tests
        run: ${{github.event.inputs.cli}}
